name: memorizer
description: Big brain time

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_local_notifications: any
  localstore: ^1.1.8
  shared_preferences: ^0.4.3
  rxdart: ^0.26.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
